from sqlalchemy import Column, String, Float, Date
from .base import Base


class StockIndicatorsSell(Base):
    """股票卖出指标"""

    __tablename__ = "cn_stock_indicators_sell"

    date = Column(Date, primary_key=True, comment="日期")
    code = Column(String(6), primary_key=True, comment="代码")
    name = Column(String(20), comment="名称")

    # rate_1 到 rate_100
    rate_1 = Column(Float, comment="1日涨跌幅")
    rate_2 = Column(Float, comment="2日涨跌幅")
    rate_3 = Column(Float, comment="3日涨跌幅")
    rate_4 = Column(Float, comment="4日涨跌幅")
    rate_5 = Column(Float, comment="5日涨跌幅")
    rate_6 = Column(Float, comment="6日涨跌幅")
    rate_7 = Column(Float, comment="7日涨跌幅")
    rate_8 = Column(Float, comment="8日涨跌幅")
    rate_9 = Column(Float, comment="9日涨跌幅")
    rate_10 = Column(Float, comment="10日涨跌幅")
    rate_11 = Column(Float, comment="11日涨跌幅")
    rate_12 = Column(Float, comment="12日涨跌幅")
    rate_13 = Column(Float, comment="13日涨跌幅")
    rate_14 = Column(Float, comment="14日涨跌幅")
    rate_15 = Column(Float, comment="15日涨跌幅")
    rate_16 = Column(Float, comment="16日涨跌幅")
    rate_17 = Column(Float, comment="17日涨跌幅")
    rate_18 = Column(Float, comment="18日涨跌幅")
    rate_19 = Column(Float, comment="19日涨跌幅")
    rate_20 = Column(Float, comment="20日涨跌幅")
    rate_21 = Column(Float, comment="21日涨跌幅")
    rate_22 = Column(Float, comment="22日涨跌幅")
    rate_23 = Column(Float, comment="23日涨跌幅")
    rate_24 = Column(Float, comment="24日涨跌幅")
    rate_25 = Column(Float, comment="25日涨跌幅")
    rate_26 = Column(Float, comment="26日涨跌幅")
    rate_27 = Column(Float, comment="27日涨跌幅")
    rate_28 = Column(Float, comment="28日涨跌幅")
    rate_29 = Column(Float, comment="29日涨跌幅")
    rate_30 = Column(Float, comment="30日涨跌幅")
    rate_31 = Column(Float, comment="31日涨跌幅")
    rate_32 = Column(Float, comment="32日涨跌幅")
    rate_33 = Column(Float, comment="33日涨跌幅")
    rate_34 = Column(Float, comment="34日涨跌幅")
    rate_35 = Column(Float, comment="35日涨跌幅")
    rate_36 = Column(Float, comment="36日涨跌幅")
    rate_37 = Column(Float, comment="37日涨跌幅")
    rate_38 = Column(Float, comment="38日涨跌幅")
    rate_39 = Column(Float, comment="39日涨跌幅")
    rate_40 = Column(Float, comment="40日涨跌幅")
    rate_41 = Column(Float, comment="41日涨跌幅")
    rate_42 = Column(Float, comment="42日涨跌幅")
    rate_43 = Column(Float, comment="43日涨跌幅")
    rate_44 = Column(Float, comment="44日涨跌幅")
    rate_45 = Column(Float, comment="45日涨跌幅")
    rate_46 = Column(Float, comment="46日涨跌幅")
    rate_47 = Column(Float, comment="47日涨跌幅")
    rate_48 = Column(Float, comment="48日涨跌幅")
    rate_49 = Column(Float, comment="49日涨跌幅")
    rate_50 = Column(Float, comment="50日涨跌幅")
    rate_51 = Column(Float, comment="51日涨跌幅")
    rate_52 = Column(Float, comment="52日涨跌幅")
    rate_53 = Column(Float, comment="53日涨跌幅")
    rate_54 = Column(Float, comment="54日涨跌幅")
    rate_55 = Column(Float, comment="55日涨跌幅")
    rate_56 = Column(Float, comment="56日涨跌幅")
    rate_57 = Column(Float, comment="57日涨跌幅")
    rate_58 = Column(Float, comment="58日涨跌幅")
    rate_59 = Column(Float, comment="59日涨跌幅")
    rate_60 = Column(Float, comment="60日涨跌幅")
    rate_61 = Column(Float, comment="61日涨跌幅")
    rate_62 = Column(Float, comment="62日涨跌幅")
    rate_63 = Column(Float, comment="63日涨跌幅")
    rate_64 = Column(Float, comment="64日涨跌幅")
    rate_65 = Column(Float, comment="65日涨跌幅")
    rate_66 = Column(Float, comment="66日涨跌幅")
    rate_67 = Column(Float, comment="67日涨跌幅")
    rate_68 = Column(Float, comment="68日涨跌幅")
    rate_69 = Column(Float, comment="69日涨跌幅")
    rate_70 = Column(Float, comment="70日涨跌幅")
    rate_71 = Column(Float, comment="71日涨跌幅")
    rate_72 = Column(Float, comment="72日涨跌幅")
    rate_73 = Column(Float, comment="73日涨跌幅")
    rate_74 = Column(Float, comment="74日涨跌幅")
    rate_75 = Column(Float, comment="75日涨跌幅")
    rate_76 = Column(Float, comment="76日涨跌幅")
    rate_77 = Column(Float, comment="77日涨跌幅")
    rate_78 = Column(Float, comment="78日涨跌幅")
    rate_79 = Column(Float, comment="79日涨跌幅")
    rate_80 = Column(Float, comment="80日涨跌幅")
    rate_81 = Column(Float, comment="81日涨跌幅")
    rate_82 = Column(Float, comment="82日涨跌幅")
    rate_83 = Column(Float, comment="83日涨跌幅")
    rate_84 = Column(Float, comment="84日涨跌幅")
    rate_85 = Column(Float, comment="85日涨跌幅")
    rate_86 = Column(Float, comment="86日涨跌幅")
    rate_87 = Column(Float, comment="87日涨跌幅")
    rate_88 = Column(Float, comment="88日涨跌幅")
    rate_89 = Column(Float, comment="89日涨跌幅")
    rate_90 = Column(Float, comment="90日涨跌幅")
    rate_91 = Column(Float, comment="91日涨跌幅")
    rate_92 = Column(Float, comment="92日涨跌幅")
    rate_93 = Column(Float, comment="93日涨跌幅")
    rate_94 = Column(Float, comment="94日涨跌幅")
    rate_95 = Column(Float, comment="95日涨跌幅")
    rate_96 = Column(Float, comment="96日涨跌幅")
    rate_97 = Column(Float, comment="97日涨跌幅")
    rate_98 = Column(Float, comment="98日涨跌幅")
    rate_99 = Column(Float, comment="99日涨跌幅")
    rate_100 = Column(Float, comment="100日涨跌幅")
