# 构建docker镜像
name: build-docker-image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        id: tagger
        name: Autotag
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          branch: main
          with-v: "true"
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: code2code-docker.pkg.coding.net
          username: ${{ secrets.CODINGHUB_USERNAME }}
          password: ${{ secrets.CODINGHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: code2code-docker.pkg.coding.net/puupees/k8s/stock:${{ steps.tagger.outputs.new-tag }}
